### ISSUE TITLE
how to customize the style

### ISSUE THREAD

**Issue by heisenberg937** [e-gor/Reveal.js-Title-Footer#5]
hello, could you please tell me how to customize the style of the footer
and what if I want add a header?

**Comment by e-gor** [comment]
> hello, could you please tell me how to customize the style of the footer

Just make the desired changes in the file plugin/title-footer/title-footer.css

>  and what if I want add a header?

The initialize function in plugin/title-footer/title-footer.js is the one that creates the footer by Javascript. You could add some similar code to add a header with the desired elements.

**Comment by heisenberg937** [comment]
Thanks
