### ISSUE TITLE
PR: Custom footer file

### ISSUE THREAD

**Issue by marcowork** [e-gor/Reveal.js-Title-Footer#6]
Since the h1 tag is used to show the footer you will have duplicated text in slide one and in your footer. 

It would be great if you can create a footer.html which can be included per section.
with it's own css

**Comment by e-gor** [comment]
You can avoid including the footer in any slide you want, including the first one, as explained in the [README](https://github.com/e-gor/Reveal.js-Title-Footer/blob/master/README.md):

> ### Exclusion from slides
> 
> The Reveal.js-Title-Footer footer will not be shown in a slide if the corresponding section has a `data-state` attribute with a value of `no-title-footer`.

Regarding CSS, you can apply the CSS you want to the footer.

So unless I have understood something wrong, I will close the issue.
